name: Main

on:
  push:
    branches: [ develop, production ]
  pull_request:
  
  
jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: General 
        run: echo github.event_name
        
      - name: Only On PR
        if: github.event_name == 'pull_request'
        run: echo github.event_name 

  check:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Inside Check
        run: echo "Oi"
