name: Main

on:
  workflow_dispatch:
    inputs:
      my_input_var:
        description: 'Some Description'
        required: true
        default: false
  push:
    branches: [ main ]
  pull_request:

env:
  MY_ENV_VAR: ${{ github.event.inputs.my_input_var && '-e pip_args==--no-cache-dir' || '' }}
  
jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: General 
        run: echo ${{github.event_name}}
        
      - name: Only On PR
        if: github.event_name == 'pull_request'
        run: echo ${{github.event_name}}
    
      - name: Set variable
        id: version
        run: echo "version_number=1.2.3" >> $GITHUB_OUTPUT
      
      - name: Consume Variable
        id: consume
        run: echo "${{ steps.version.outputs.version_number }}"
      
      - name: Debug
        run: echo "${{ env.MY_ENV_VAR }}"
        
      - name: Conditional Step
        if: github.event_name == 'push' || ${{ env.MY_ENV_VAR }}
        run: echo "${{ env.MY_ENV_VAR }}"
