name: Main

on:
  push:
    branches: [ main ]
  pull_request:

  
jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: General 
        run: echo ${{github.event_name}}
        
      - name: Only On PR
        if: github.event_name == 'pull_request'
        run: echo ${{github.event_name}}
    
      - name: Set variable
        id: version
        run: echo "::set-output name=version_number::1.2.3"
      
      - name: Consume Variable
        id: consume
        run: echo "${{ steps.version.outputs.version_number }}"
