name: Main

on:
  workflow_dispatch:
    inputs:
      my_input_var:
        description: 'Deploy with pip caching disabled'
        type: choice
        options: 
        - 'true'
        - 'false'
        default: 'false'
  push:
    branches: [ main ]
  pull_request:

env:
  MY_ENV_VAR: ${{ github.event.inputs.my_input_var == 'true' && '-e "pip_args==--no-cache-dir"' || '' }}
  SHA_VALUE: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.sha) || github.sha }}"
  
jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: General 
        run: echo ${{github.event_name}}
        
      - name: Only On PR
        if: github.event_name == 'pull_request'
        run: echo ${{github.event_name}}
    
      - name: Set variable
        id: version
        run: echo "version_number=1.2.3" >> $GITHUB_OUTPUT
      
      - name: Consume Variable
        id: consume
        run: echo "${{ steps.version.outputs.version_number }}"
      
      - name: Debug
        run: |
          echo ${{ env.MY_ENV_VAR }}
          echo ${{ env.SHA_VALUE }} 
          echo ${{ github.event.inputs.my_input_var }}
          echo ${{ github.event.inputs.my_input_var == 'true' }}
          echo ${{ github.event_name == 'push'}}
          echo ${{github.event_name}}
          echo "${{github.event_name == 'push' || github.event.inputs.my_input_var == 'true' }}"
        
      - name: Get SHA version
        id: sha-version
        shell: bash
        run: echo "version=${{ (github.event_name == 'pull_request' && github.event.pull_request.head.sha) || github.sha }}" >> $GITHUB_OUTPUT

      - name: Generate semver version
        id: semantic-version
        shell: bash
        run: echo "${{ steps.sha-version.outputs.version }}"
          
        
      - name: Conditional Step
        if: ${{ github.event.inputs.my_input_var == 'true'  || github.event_name == 'push' }} # a single comment
        run: pip install "${{ env.MY_ENV_VAR }}" requests
