name: Main

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '*/5 * * * *'  #  every friday at 9 a.m.
  
jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: General 
        run: echo ${{github.event_name}}
        
      - name: Only On PR
        if: github.event_name == 'pull_request'
        run: echo ${{github.event_name}}

  check:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Inside Check
        run: echo ${{github.event_name}}
  
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: [check]
    if: github.event_name == 'push'
    
    steps:
      - name: Build 
        run: echo ${{github.event_name}}
